server:
  port: 8090

spring:

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
        timeout: 10000
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  devtools:
    restart:
      enabled: true  #???????
  freemarker:
    cache: false    #??????????????
  web:
    resources:
      static-locations: classpath:/static/

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # ???????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # ??SQL??
  mapper-locations: classpath:mapper/*.xml

